config/routes.rb
Rails.application.routes.draw do
  get 'events/index'
  resources :users
  root 'events#index'
  resources :events
  delete '/logout',  to: 'sessions#destroy'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  post   '/attend',  to: 'attendances#create'
  get    'attendances', to: 'attendances#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
# frozen_string_literal: true

class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :user_id, presence: true
  validates :event_id, presence: true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :user
  has_many :attendances, dependent: :destroy
  validates :title, presence: { string: true }, length: { minimum: 4 }
  validates :description, presence: { text: true }, length: { minimum: 10 }
  validates :date, presence: { date: true }
  validate :date_cannot_be_in_the_past
  validates :location, presence: { string: true }, length: { minimum: 4 }
  validates :user_id, presence: true
  scope :upcoming_events, -> { where('date >  ?', Date.today) }
  scope :past_events, -> { where('date < ? ', Date.today) }
  scope :today_events, -> { where('date = ? ', Date.today) }
  default_scope { order(date: :desc) }

  def date_cannot_be_in_the_past
    errors.add(:date, 'date cannot be in the past') if date.present? && date < Date.today
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save :downcase_email
  has_many :events, dependent: :destroy
  has_many :attendances, dependent: :destroy
  validates :name, presence: { string: true }, length: { minimum: 2 }
  validates :password_digest, presence: { string: true }, length: { minimum: 4 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  def downcase_email
    self.email = email.downcase
  end

  def self.digest(_string)
    if ActiveModel::SecurePassword.min_cost
      BCrypt::Engine::MIN_COST
    else
      BCrypt::Engine.cost
    end
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def logged_in_user
    return if logged_in?

    store_location
    flash[:danger] = 'Please log in.'
    redirect_to login_url
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/controllers/attendances_controller.rb
# frozen_string_literal: true

class AttendancesController < ApplicationController
  before_action :logged_in_user, only: %i[new create]
  def index
    @attendances = Attendance.all
  end

  def new
    @attendance = Attendance.new(params[:event_id])
  end

  def create
    @attendance = Attendance.new(attendance_params)
    @attendance.attendee = current_user.name
    # @attendance.event_id = current_user.event_id
    @attendance.user_id = current_user.id
    if @attendance.save
      redirect_to attendances_path
    else
      flash.now[:danger] = 'Attendance was not created'
      render 'index'
    end
  end

  private

  def set_attendance
    @attendance = Attendance.find(params[:id])
  end

  def attendance_params
    params.permit(:event_id)
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :logged_in_user, only: %i[new create edit]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      redirect_to events_path
    else
      flash.now[:danger] = 'Event was not created'
      render 'new'
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :date, :location)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user
      log_in user
      redirect_to events_path
    else
      flash.now[:danger] = 'Invalid email'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def show
    log_in(@user)
    @upcoming_events = Event.all.upcoming_events
    @past_events = Event.all.past_events
    @today_events = Event.all.today_events
    @attendances = Attendance.all
    @attended_events = Event.all.past_events
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password_digest)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/attendances_helper.rb
# frozen_string_literal: true

module AttendancesHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session[:user_id] = nil
    @current_user = nil
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/attendances/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-12 text-center mt-4">
      <h1> Attendances</h1>
    </div>
    <table class="table col-12 text-center">
      <thead class="thead-dark">
        <tr>
          <th>Event</th>
          <th>Date</th>
          <th>Location</th>
          <th>Creator</th>
          <th>Attendee</th>
        </tr>
      </thead>
      <tbody>
           <% @attendances.each do |attendance|%>
          <tr>
          <td><%= attendance.event.title %></td>
          <td><%= attendance.event.date %></td>
          <td><%= attendance.event.location %></td>
          <td><%= attendance.event.user.name %> </td>
          <td><%= attendance.attendee %></td>
          </tr>
          <% end %>
      </tbody>
    </table>

</div>

app/views/events/_form.html.erb
  <div class="col-12">
    <%= form_with(model: event, local: true , :class => "form") do |form| %>
      <% if event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(event.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group text-left">
        <%= form.label :title %>
        <%= form.text_field :title , :class => "form-control"%>
      </div>

      <div class="form-group text-left">
        <%= form.label :description %>
        <%= form.text_field :description, :class => "form-control"%>
      </div>

      <div class="form-group text-left">
        <%= form.label :date %>
        <%= form.text_field :date, :class => "form-control",  "data-provide" => 'datepicker' %>
      </div>

      <div class="form-group text-left">
        <%= form.label :location %>
        <%= form.text_field :location, :class => "form-control" %>
      </div>

      <div class="actions">
        <%= form.submit :class => "btn btn-success mt-2"%>
      </div>
    <% end %>
  </div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-12 text-center mt-4">
      <h1> Events</h1>
    </div>
    <table class="table col-12 text-center mt-3">
      <thead class="thead-dark">
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Date</th>
          <th>Location</th>
          <th>Creator</th>
          <th>Go</th>
        </tr>
      </thead>
      <tbody>
           <% @events.each do |event|%>
          <tr>
            <td class="align-middle"><%= event.title %></td>
            <td class="align-middle"><%= event.description %></td>
            <td class="align-middle"><%= event.date %></td>
            <td class="align-middle"><%= event.location %></td>
            <td class="align-middle"><%= event.user.name %></td>
            <% if logged_in? and event.date >= Date.today %>
                <td><%= link_to 'Attend', attend_path(:event_id => event.id) ,method: :post, :class => "btn  btn-outline-primary mt-2" %></td> 
            <% end %>
          </tr>
          <% end %>
          
          </tr>
      </tbody>
    </table>
<div class="col-12 text-center mt-3">
    <div class="footer text-center  pt-3 pb-3">
      <%= link_to 'New Event', new_event_path , :class => "btn btn-success mt-2" %>

    </div>
  </div>
</div>

app/views/events/new.html.erb
<% provide(:title, "New Event") %>
<div class="container">
    <div class="row">
        <div class="col-12 text-center mt-4">
            <h1>New Event</h1>
        </div>
        <div class="col-2 col-lg-d-none"></div>

        <div class="col-8 text-center">
             <%= render 'form', event: @event %> 
        </div>
        <div class="col-2 col-lg-d-none"></div>

       
    </div>
</div> 

app/views/layouts/_footer.html.erb
<nav class="navbar fixed-bottom navbar-expand navbar-light bg-light">


<!-- Brand -->
<a class="navbar-brand" href="#">DoneBy : </a>

<!-- Links -->
<div class="collapse navbar-collapse" id="nav-content">   
<ul class="navbar-nav">
<li class="nav-item">
<a class="nav-link" href="https://github.com/AlejoCode">Alejandro Salgado</a>
</li>
<li class="nav-item">
<a class="nav-link" href="https://github.com/gonjavi">Gonzalo J. Mancila</a>
</li>

</ul>
</nav></a>

app/views/layouts/_header.html.erb
    <%= csrf_meta_tags %>

<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <div class="navbar-header d-none d-md-block">
      <a class="navbar-brand" href="#">DB Associations</a>
    </div>
    
       
      
    <form class="form-inline">
     <ul class="nav">
          <li class="nav-item pr-3"><%= link_to "Attendances", attendances_path %></li>
          <li class="nav-item pr-3"><%= link_to "Events", events_path %></li>
        </ul>
    <% if logged_in? %>
      <a class="btn btn-outline-primary" href="/users/<%= current_user.id %>" role="button">
        Hi <%= current_user.name %>
      </a>
      <div style="padding-left: 10px;">

        <%= link_to "Log out", logout_path, method: :delete , :class => "btn btn-outline-danger"%>
      </div>
    <% else%>

      <a class="btn btn-outline-primary" href="/login" role="button">
      Login
      </a>
      <div style="padding-left: 10px;">
        <a class="btn btn-outline-success" href="/users/new " role="button">
        Sign Up
        </a>
      </div>
    <% end %>

    </form>
  </div>
</nav>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   
   
  

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authapp</title>
      <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="row">
        <div class="col-12 text-center">
          <%= yield %>
        </div>
      </div>
    </div>
    
    </body>
  <%= render 'layouts/footer' %>

</html>

app/views/users/_form.html.erb
<div class="col-12">
  <%= form_with(model: user, local: true , :class => "form") do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group text-left">
      <%= form.label :name %>
      <%= form.text_field :name , :class => "form-control"%>
    </div>

    <div class="form-group text-left">
      <%= form.label :email %>
      <%= form.text_field :email , :class => "form-control"%>
    </div>

    <div class="form-group text-left">
      <%= form.label :password %>
      <%= form.password_field :password_digest, :class => "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit :class => "btn btn-success mt-2"%>
    </div>
  <% end %>

</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

      <h1 class="mt-5">Private Events</h1>

      <table class="table table-dark mt-5">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col"></th>

            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr >
              <% if user == current_user %>
              <td class="align-middle"><%= user.name %></td>
              <td class="align-middle"><%= user.email%></td>
              <td class="align-middle"><%= link_to 'My Events', user , :class => "btn btn-outline-info align-middle"%></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New User', new_user_path , :class => "btn btn-success mt-3"%>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<div class="container">
    <div class="row">
        <div class="col-12 text-center mt-4">
            <h1>New User</h1>

        </div>
        <div class="col-2 col-lg-d-none"></div>

        <div class="col-8 text-center">

            <%= render 'form', user: @user %>
        </div>
        <div class="col-2 col-lg-d-none"></div>

        <div class="col-12 text-center mt-5">
            <div class="footer text-center bg-light pt-3 pb-3">
            <%= link_to 'Back', users_path , :class => "btn btn-outline-secondary"%>

            </div>
        </div>
    </div>
</div> 

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-12 text-center mt-4">
      <h1>  <%= @user.name %>'s Events</h1>
    </div>

    <table class="table col-12 text-center">
      <div class="col-12 text-center mt-4">
      <h3>Created Events </h3>
    </div>
      <thead class="thead-dark mt-4">
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Date</th>
          <th>Location</th>
          <th>Creator</th>
        </tr>
      </thead>
      <tbody>
      
      <% @user.events.each do |event|%>
          <tr>
            <% if event.user_id == current_user.id %>
            <td><%= event.title %></td>
            <td><%= event.description %></td>
            <td><%= event.date %></td>
            <td><%= event.location %></td>
            <td><%= event.user.name %></td>  
            <% end %>         
          </tr>
          <% end %>
      </tbody>
    </table>

    <table class="table col-12 text-center">
      <div class="col-12 text-center mt-4">
      <h3>Going</h3>
    </div>
      <thead class="thead-dark mt-4">
        <tr>
          <th >Title</th>
          <th >Description</th>
          <th >Date</th>
          <th >Location</th>
          <th>Creator</th>
          <th>Attendee</th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |attendance|%>
          <tr>
          <% if attendance.user_id == current_user.id and attendance.event.date >= Date.today %>
          <td><%= attendance.event.title %></td>
          <td><%= attendance.event.description %></td>
          <td><%= attendance.event.date %></td>
          <td><%= attendance.event.location %></td>
          <td><%= attendance.event.user.name %> </td>
          <td><%= attendance.attendee %></td>
          <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <table class="table col-12 text-center">
    <div class="col-12 text-center mt-4">
    <h3>Todays Events</h3>
  </div>
    <thead class="thead-dark mt-4">
       <tr>
        <th >Title</th>
        <th >Description</th>
        <th >Date</th>
        <th >Location</th>
        <th>Creator</th>
      </tr>
    </thead>
    <tbody>
        <% @today_events.each do |event|%>
        <tr>
          <td><%= event.title %></td>
          <td><%= event.description %></td>
          <td><%= event.date %></td>
          <td><%= event.location %></td>
          <td><%= event.user.name %></td>  
        </tr>
        <% end %>
  </table>


    <table class="table col-12 text-center">
      <div class="col-12 text-center mt-4">
      <h3>Upcoming Events</h3>
    </div>
      <thead class="thead-dark mt-4">
         <tr>
          <th >Title</th>
          <th >Description</th>
          <th >Date</th>
          <th >Location</th>
          <th>Creator</th>
        </tr>
      </thead>
      <tbody>
          <% @upcoming_events.each do |event|%>
          <tr>
            <td><%= event.title %></td>
            <td><%= event.description %></td>
            <td><%= event.date %></td>
            <td><%= event.location %></td>
            <td><%= event.user.name %></td>  
          </tr>
          <% end %>
    </table>

    <table class="table col-12 text-center">
      <div class="col-12 text-center mt-4">
      <h3>Past Events</h3>
    </div>
      <thead class="thead-dark mt-4">
        <tr>
          <th >Title</th>
          <th >Description</th>
          <th >Date</th>
          <th >Location</th>
          <th>Creator</th>
        </tr>
      </thead>
      <tbody>
           <% @past_events.each do |event|%>
          <tr>
            <td><%= event.title %></td>
            <td><%= event.description %></td>
            <td><%= event.date %></td>
            <td><%= event.location %></td>
            <td><%= event.user.name %></td>  
          </tr>
          <% end %>
      </tbody>
    </table>

  <div class="col-12 text-center mt-5">
    <div class="footer text-center  pt-3 pb-3">
      <%= link_to 'New Event', new_event_path , :class => "btn btn-success mt-2" %>

    </div>
  </div>
</div>